## Numpy 기초
- Numpy를 사용 : 데이터 사이언스에서 사용하는 중요한 패키지<br>
- Numpy 다음에는 <b style="color:red">Pandas</b>를 배워서 데이터 전처리 작업을 한다.
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/330px-NumPy_logo.svg.png">

### 1. 정수자료형 처리

In [8]:
import numpy as np

In [10]:
math1 = 80
math2 = 95
math3 = 75

In [11]:
m_sum = math1 + math2 + math3
m_avg = m_sum / 3

In [12]:
print("수학 점수의 합계 : {}".format(m_sum))
print("수학 점수의 평균 : {}".format(m_avg))

수학 점수의 합계 : 250
수학 점수의 평균 : 83.33333333333333


In [13]:
math4 = 87

In [14]:
m_sum = math1+math2+math3+math4
m_avg = m_sum / 4

In [15]:
print("수학 점수의 합계 : {}".format(m_sum))
print("수학 점수의 평균 : {}".format(m_avg))

수학 점수의 합계 : 337
수학 점수의 평균 : 84.25


### 2. 리스트자료형으로 처리

In [35]:
mlist = [89,95,75]
print(mlist)

[89, 95, 75]


In [36]:
m_sum1 = 0
m_avg1 = 0

In [37]:
# for문을 이용해서 합계 평균 구하기
for e in mlist:
    m_sum1 += e

m_avg1 = m_sum1 / len(mlist)

In [38]:
print("수학 점수의 합계1 : {}".format(m_sum1))
print("수학 점수의 평균1 : {}".format(m_avg1))

수학 점수의 합계1 : 259
수학 점수의 평균1 : 86.33333333333333


In [39]:
mlist.append(87)

print(mlist)

[89, 95, 75, 87]


In [40]:
m_sum1 = 0
m_avg1 = 0
# for문을 이용해서 합계 평균 구하기
for e in mlist:
    m_sum1 += e

m_avg1 = m_sum1 / len(mlist)

In [41]:
print("수학 점수의 합계1 : {}".format(m_sum1))
print("수학 점수의 평균1 : {}".format(m_avg1))

수학 점수의 합계1 : 346
수학 점수의 평균1 : 86.5


####  3) 문제발생 : 채점에 문제가 생겨 모든 학생의 점수를 모두 1점씩 상향해서 올려줘야하는 일이 발생

In [1]:
mlist = [89, 95, 75, 87]
m_sum1 = 0
m_avg1 = 0

# for문을 이용해서 합계 평균 구하기
for e in mlist:
    m_sum1 += e
    
m_avg1 = m_sum1 / len(mlist)

print("수학 점수 합계 : {}".format(m_sum1))
print("수학 점수 평균 : {}".format(m_avg1))

수학 점수 합계 : 346
수학 점수 평균 : 86.5


In [2]:
### 문제 해결 -> 1점 더하기
mlist_new = [e + 1 for e in mlist]
print(mlist_new)

[90, 96, 76, 88]


In [3]:
# for문을 이용해서 합계 평균 구하기
m_sum2 = 0
m_avg2 = 0

for e in mlist_new:
    m_sum2 += e

m_avg2 = m_sum2 / len(mlist_new)

print("수학 점수 합계 2 : {}".format(m_sum2))
print("수학 점수 평균 2 : {}".format(m_avg2))

수학 점수 합계 2 : 350
수학 점수 평균 2 : 87.5


### 4) 학생수의 증가로 3반으로 증가했다고 가정 ==> 한 반에 4명씩 3반이 생겼다!

- 1반 : 10, 20, 30, 40
- 2반 : 21, 22, 23, 24
- 3반 : 31, 32, 33, 34

In [44]:
nested_mlist = [[10, 20, 30, 40],[21, 22, 23, 24],[31, 32, 33, 34]]

nested_mlist_new = []

#for tmp in nested_mlist:
#    nested_mlist_new.append([e+1 for e in tmp]) 

nested_mlist_new = [[e+1 for e in tmp] for tmp in nested_mlist]

print(nested_mlist)
print(nested_mlist_new)

[[10, 20, 30, 40], [21, 22, 23, 24], [31, 32, 33, 34]]
[[11, 21, 31, 41], [22, 23, 24, 25], [32, 33, 34, 35]]


### Numpy 패키지로 해결하기
- 파이썬으로 만든 수치계산 패키지(데이터 분석)
- 내부는 C로 만들어져 있어서 계산 속도가 엄청 빠르다.
- 데이터 타입을 한가지만 허용
- I = [1,1.5,'hong',[1,2,3,4]] 은 안됨
- Array 형태의 데이터 처리 : 선형대수학

In [46]:
l = [1,1.5,"hong",[1,2,3,4]] #파이썬 리스트
print(l)

[1, 1.5, 'hong', [1, 2, 3, 4]]


In [47]:
import numpy as np # 파이썬 배열을 이용해서 numpy 배열을 만듬

In [49]:
print(np.__version__)

1.18.1


In [82]:
# 단일 값 : 스칼라
a = np.array(10)
print(a)
print(a.dtype) # a의 타입, type(a)
print(a.ndim) # a의 차원
print(a.shape) # ?행, ?열
print(a.nbytes) # 4byte
print(a.size) # 크기?

10
int32
0
()
4
1


In [78]:
# 1차원 배열
b = np.array([1,2,3,4])
print(b)
print(b.dtype)
print(b.ndim)
print(b.shape)
print(b.nbytes)
print(b.size)

[1 2 3 4]
int32
1
(4,)
16
4


In [79]:
# 2차원 배열 (3 x 2)
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c.dtype)
print(c.ndim)
print(c.shape)
print(c.nbytes)
print(c.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32
2
(3, 3)
36
9


In [80]:
# 3차원 배열 (3 x 2 x 3)
d = np.array(
    [
        [
            [1,2,3],[4,5,6]
        ],
        [
            [7,8,9],[10,11,12]
        ],
        [
            [13,14,15],[16,17,18]
        ]
    ])
print(d)
print(d.dtype)
print(d.ndim)
print(d.shape)
print(d.nbytes)
print(d.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int32
3
(3, 2, 3)
72
18


In [94]:
# numpy는 배열에 다른 타입의 데이터를 허용하지 않음
test_arr = np.array([1,4,"5","8"], dtype=np.float)

print(test_arr)
print(test_arr.dtype)
print(test_arr.ndim)
print(test_arr.shape)
print(test_arr.nbytes)
print(test_arr.size)

[1. 4. 5. 8.]
float64
1
(4,)
32
4


In [101]:
test_arr1 = np.array(range(1,10), dtype=np.int32)
test_arr2 = np.arange(1,11) # 이상,미만
print(test_arr1)
print(test_arr2)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [102]:
test_arr3 = np.arange(1,11,0.5) # arange 함수는 1차원의 배열 생성
print(test_arr3)
print("개수 : {}".format(test_arr3.size))

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
개수 : 20


In [107]:
test_arr4 = np.arange(1,11,0.5)

test_arr4 = test_arr4.reshape(10,2)
print(test_arr4)

test_arr4 = test_arr4.reshape(4,5)
print(test_arr4)

[[ 1.   1.5]
 [ 2.   2.5]
 [ 3.   3.5]
 [ 4.   4.5]
 [ 5.   5.5]
 [ 6.   6.5]
 [ 7.   7.5]
 [ 8.   8.5]
 [ 9.   9.5]
 [10.  10.5]]
[[ 1.   1.5  2.   2.5  3. ]
 [ 3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8. ]
 [ 8.5  9.   9.5 10.  10.5]]
